//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CPRICE_WXCRAFTER_BASE_CLASSES_H
#define CPRICE_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include <wx/richtext/richtextctrl.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxStaticText* m_staticText19;
    wxTextCtrl* m_textCtrlFolder;
    wxButton* m_buttonSelect;
    wxRichTextCtrl* m_richTextMsg;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_menuPrice;
    wxMenuItem* m_menuItemProcess;
    wxMenu* m_menuTA;
    wxMenuItem* m_menuItemTACheckTA;
    wxMenuItem* m_menuItemSort;
    wxMenuItem* m_menuItemCombineData;
    wxMenuItem* m_menuItem41;
    wxMenuItem* m_menuItemTA;
    wxMenuItem* m_menuItemEMP;
    wxMenuItem* m_menuItemLT;
    wxMenuItem* m_menuItemLCT;
    wxMenuItem* m_menuItemSALE;
    wxMenuItem* m_menuItemMKVALT;
    wxMenuItem* m_menuItemEPS;
    wxMenu* m_menuNew3;
    wxMenuItem* m_menuItemRETURNONP;
    wxMenuItem* m_menuItemDPRATIO;
    wxMenuItem* m_menuItemMARGINS;
    wxMenu* m_nameHelp;
    wxMenuItem* m_menuItem9;
    wxToolBar* m_mainToolbar;

protected:
    virtual void OnSelectFolder(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnPriceProcess(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTACheckTA(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTASortAt(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTACombineData(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessTA(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessEMP(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessLT(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessLCT(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessSALE(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessMKVALT(wxCommandEvent& event) { event.Skip(); }
    virtual void OnProcessEPS(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRETURNONP(wxCommandEvent& event) { event.Skip(); }
    virtual void OnDPRATIO(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMARGINS(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText19() { return m_staticText19; }
    wxTextCtrl* GetTextCtrlFolder() { return m_textCtrlFolder; }
    wxButton* GetButtonSelect() { return m_buttonSelect; }
    wxPanel* GetMainPanel() { return m_mainPanel; }
    wxRichTextCtrl* GetRichTextMsg() { return m_richTextMsg; }
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxToolBar* GetMainToolbar() { return m_mainToolbar; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
